[package]
name = "rust-snmp-collector"
version = "0.1.0"
edition = "2018"

authors = ["Armin Fisslthaler <armin@fisslthaler.net>"]
license = "GPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
config-file = { version = "0.2.1", features = [ "yaml" ] }
crossbeam-channel = "0.5.1"
env_logger = "0.9.0"
failure = "0.1.8"
log = "0.4.14"
mib_parser = { git = "https://github.com/afics/mib-parser", rev = "0778cc5b842ab9f43e74c2d2eaf41b215b76eda9" }
msnmp = { git = "https://github.com/afics/modern_snmp", rev = "4e376d3546b48c2a35a50bb6f64e539ba6509024" }
rand = "0.8.4"
scan_dir = "0.3.3"
serde = { version = "1.0.130", features = [ "derive" ] }
size_format = "1.0.2"
snmp_mp = { git = "https://github.com/afics/modern_snmp", rev = "4e376d3546b48c2a35a50bb6f64e539ba6509024" }
snmp_usm = { git = "https://github.com/afics/modern_snmp", rev = "4e376d3546b48c2a35a50bb6f64e539ba6509024" }

